### ISSUE TITLE
Неверное отображение графиков

### ISSUE THREAD

**Issue by skr0y** [JavaZenTeam/IgorBot#23]
На графиках на странице статистики дни/часы без значений никак не отображаются. Надо считать их нулями.

**Comment by Daemon712** [comment]
Пофиксил для случая когда за период нет статистики за некоторых юзеров. Но если за период нет статистики вообще, отображаться данные все равно не будут.
Связано это со спецификой запроса в базу данных. Альтернативного варианта запроса я не придумал. К решению на стороне джава кода не хочется, т.к. будет некрасиво

**Comment by skr0y** [comment]
Сойдет, нам не надо постоянно видеть всяких Антонов
