### ISSUE TITLE
Сделать подгрузку статистики по словам по запросу

### ISSUE THREAD

**Issue by skroychan** [JavaZenTeam/IgorBot#47]
Сейчас она грузится всегда и сразу, и очень медленно. Используется фича редко, так что надо сделать кнопку для подгрузки или отдельную вкладку

**Comment by Daemon712** [comment]
или выпилить совсем?

**Comment by skroychan** [comment]
или выпилить совсем 😔

**Comment by asmal95** [comment]
Выпилить +

**Comment by Daemon712** [comment]
выпилено
