### ISSUE TITLE
Ограничение доступа к странице статитики

### ISSUE THREAD

**Issue by Daemon712** [JavaZenTeam/IgorBot#6]
Описать, каким образом можно ограничить доступ к странице. Чтобы люди не могли просматривать статистику чатов, в которых не состоят

**Comment by Daemon712** [comment]
@asmal95 есть идеи? 

думаю, можно добавить ключ к url, то есть открыть страницу можно будет только по урлу вида http://javazen.ru/IgorBot/chat/-1001063148517?token=ABCD123123

**Comment by Daemon712** [comment]
Но технически как это реализовать, я пока не знаю

**Comment by asmal95** [comment]
Текущий подход: генерация токена на запрос статистики. При переходе по ссылке создается объект 
 аутентификации для доступа к конкретному чату и помещается в текущую сессию. 
Коммит: https://github.com/JavaZenTeam/IgorBot/commit/fc0d74fee32b3c5ca8397282841f1ff0ae2fa6a2
