### ISSUE TITLE
Ограничить число отображаемых записей на странице статистики

### ISSUE THREAD

**Issue by Daemon712** [JavaZenTeam/IgorBot#65]
Когда записей больше 6, уже сложно разбирать данные на графике, да и таблица слишком сильно разъезжается

**Comment by skroychan** [comment]
6 - не слишком ли маленькой ограничение? В идеале бы, конечно, на страницы разделять, но спроса нет.

**Comment by Daemon712** [comment]
Ограничение можно сделать более умное
Страницу не очень, есть идея получше, потом покажу)
